[clang-tidy] add explicit to single argument constructors
ninja-build/ninja pull request #1791
Opened 2020-06-03 20:23 UTC by neheb

Found with google-explicit-constructor

Signed-off-by: Rosen Penev <rosenp@gmail.com>

2020-06-03 20:58 UTC, jonesmz commented
:+1:

2020-12-05 22:39 UTC, jhasse requested changes
Can you add it to .clang-tidy, too?

2020-12-05 22:39 UTC, jhasse commented on src/build_test.cc
>                              builder_(&state_, config_, NULL, log, &fs_),
clang-format

2020-12-05 23:49 UTC, neheb commented
Done.

2020-12-06 06:16 UTC, neheb commented
I think I'll remove that.

It also complains on string_piece.h , which causes all sorts of errors.

2020-12-06 11:15 UTC, merged