Revert #1753 and add additional tests to expose previously untested behavior
ninja-build/ninja pull request #1935
Opened 2021-03-23 20:23 UTC by jdrouhard

This reverts #1753 with the intention of re-landing the change with the fixes from #1933.

Additional tests are included that recreate some CMake test suite tests (see #1932). These regression tests are useful since they expose some edge-casey behavior.

2021-03-23 20:24 UTC, jdrouhard commented
cc: @jhasse @bradking

2021-03-24 13:02 UTC, bradking requested changes
The revert looks correct.  The test cases are representative of what we discussed in #1932 and #1933.

I've made some minor comments that need addressing.

Also, please update the revert's commit message to mention that it fixes issue #1932.

2021-03-24 13:42 UTC, jdrouhard commented on src/build_test.cc
> +"  depfile = out.d\n"));
I thought I'd updated all these to use the `test_dependency` binding. Must have missed this one in the cherry-pick.

2021-03-24 13:47 UTC, jdrouhard commented on src/build_test.cc
> +"  depfile = out.d\n"));
Done.

2021-03-24 13:48 UTC, jdrouhard commented on src/build_test.cc
> +    "  command = touch $out; echo \"$out: $test_dependency\" > $depfile\n"
done

2021-03-24 14:13 UTC, bradking approved these changes

2021-03-24 15:22 UTC, merged