Make the output of `ninja -t inputs` deterministic
ninja-build/ninja pull request #2075
Opened 2022-02-03 15:39 UTC by digit-google

This sorts the output of `ninja -t inputs` to make it
deterministic and remove duplicates.

2022-02-05 12:39 UTC, jhasse commented
LGTM

@naarcini what do you think?

2022-02-07 18:23 UTC, naarcini approved these changes
Generally LGTM % a couple of suggestions

2022-02-07 19:08 UTC, digit-google commented on src/ninja.cc
> +  // Make output deterministic by sorting then removing duplicates.
I think I'm confused, I though std::unique was not part of C++03 !? if it is I would gladly use it (the code is based on the implementation example on https://en.cppreference.com/w/cpp/algorithm/unique)

2022-02-07 19:54 UTC, naarcini commented on src/ninja.cc
> +  // Make output deterministic by sorting then removing duplicates.
I found it difficult to find good documentation about what is or isn't in C++03, but I believe std::unique is present. I'm basing this partly on the cppreference page for the algorithm library, which annotates which version of C++ particular functions were added (no annotation for `unique`):
https://en.cppreference.com/w/cpp/algorithm

And partly by clicking through the gcc github repo, which includes an implementation for std::unique in version 2.95 (last edited 1998):
https://github.com/gcc-mirror/gcc/blob/releases/gcc-2.95/libstdc%2B%2B/stl/stl_algo.h

2022-02-07 23:48 UTC, digit-google commented
I have added a unit-test for Edge::CollectInputs. It seems there are no good ways to test tools though. Should we want to add these, should we go with regression tests (e.g. scripts that invoke Ninja with pre-determined build plans, and verify behaviour), or refactor ninja.cc to make tools unit-testable? Probably  not in this PR though :-)

2022-02-08 10:11 UTC, jhasse commented
Some very basic regression tests are in `misc/output_test.py`, e.g.: https://github.com/ninja-build/ninja/blob/cd967ab21eef51819473b0cea22135fead76ffc2/misc/output_test.py#L117

Making tools unit-testable is probably a good idea though.

2022-02-08 13:58 UTC, digit-google commented
Thanks, I could add a regression test to `output_test.py` for the new tool.

I'm still concerned about the fact that we do not include implicit inputs in the the tool's output. The fact that they are not listed in the command line itself doesn't make them less important. And I don't see a use case where you would want only the explicit inputs anyway. should we add an "explicit-inputs" tool for these otherwise?

2022-02-10 17:46 UTC, naarcini commented
@digit-google In my specific use case, we only needed the explicit dependencies. At the time, I was trying to improve upon a project in Chromium that audits certain metadata in code (Network Traffic Annotation Auditor). In that case, all I needed was specifically the code files that are used to build a particular target. Since Chromium's tooling does a pretty good job of explicitly listing all dependencies, I found that "explicit" was enough to fulfill this requirement.

I'm not opposed to adding an additional flag or changing the default behavior to include more information. That'd still work fine for my use case and I suspect it'd work fine for most other peoples' use cases too. If I get a vote, I vote for using an additional flag instead of multiple tool names :)

2022-02-11 13:42 UTC, digit-google commented
Latest update adds `--type=TYPE` option to the tool, as in `-t inputs --type=TYPE <targets>`. The default is to print explicit + implicit inputs, but this can be changed with `--type=explicit` and `--type=all`. I think that should address all use cases now :)

2022-02-17 09:53 UTC, digit-google commented
Friendly ping, anything else to get this merged? I would really prefer if the existing behavior was not part of the next 1.11 release :-/

2022-02-20 13:57 UTC, jhasse commented
The `--type` flag needs to be split into its own commit. But before you do that: Is the flag really necessary? I would like to keep the inputs tool simple for the moment.

Also:

> (i.e. this allows us to skip any stale outputs from a previous build, since cleandead will not work in certain cases).

Sounds like a bug of the cleandead tool?

2022-02-21 15:04 UTC, digit-google commented
Well, I have a use case where I need all implicit + explicit dependencies, and @naarcini only wants the explicit ones, so a `--type` flag seems the better option here.

This is not really a bug in `cleandead`, it is more a Ninja design issue: the `.ninja_deps` file will record all entries generated by depfiles, and sometimes, some of them will be stale (because a command changed and will no longer use that file to the build and the corresponding depfile). Ninja has no way to detect these cases before re-running the build, so `cleandead` will always keep the stale files in the build directory. This has been causing a variety of breakages in our incremental builds (e.g. https://fxbug.dev/83397 or more recently https://fxbug.dev/85465.

This tool would be one of the different ways we want to work around this problem.

I'll update the PR to make the `--type  flag its own commit.

2022-02-25 15:38 UTC, jhasse requested changes
> and @naarcini only wants the explicit ones

If I understood him correctly, he wouldn't mind the implicit ones, but doesn't need them?

The extra `InputsType` struct is quite a lot of code and I only merged the inputs tool because it was such a small change.

2022-02-25 15:38 UTC, jhasse commented on src/graph_test.cc
> +  edge->CollectInputs(false, InputsType::Default, &inputs);
This needs to be part of the second commit.

2022-02-25 15:38 UTC, jhasse commented on src/ninja.cc
> +      kNinjaVersion, config.parallelism);
Why this change?

2022-02-25 15:38 UTC, jhasse commented on src/ninja.cc
> +void CollectInputs(Edge* edge, set<Edge*>* seen,
while you're at it, can you add `std::` here?

2022-02-25 15:38 UTC, jhasse commented on src/ninja.cc
> +#include <algorithm>
can you move this include to the top?

2022-02-25 15:38 UTC, jhasse commented on src/ninja.cc
> +#include "deps_log.h"
any reason for this reordering?

2022-02-25 15:38 UTC, jhasse commented on src/ninja.cc
> -          "List all inputs used for a set of targets. Note that this ignores\n"
The "List all inputs used for a set of targets." shouldn't be removed, right?

2022-03-07 12:00 UTC, digit-google commented
I pushed a new version with the changes you requested 10 days ago, but forgot to submit my review comments, which I just did. Sorry. Let me know if there is something else to do to get this submitted. Thanks.

2022-03-17 16:29 UTC, jhasse reviewed
I still think that the tool shouldn't include the `--type` option and always print all inputs, at least for 1.11.0.

2022-03-17 16:29 UTC, jhasse commented on src/ninja.cc
> +#include "deps_log.h"
I see. Can you still move it back? Best to avoid unnecessary noise in the diff.

2022-03-17 16:29 UTC, jhasse commented on src/ninja.cc
> +  // clang-format off
Please don't add those, clang-format is not enforced in Ninja's code base.

2022-03-18 17:04 UTC, digit-google commented
Done, let me know what you think :)

2022-03-21 13:56 UTC, digit-google commented
I have refactored the two commits so that the first one would print all inputs in a deterministic way (and update the documentation), while the second one adds the `--type=TYPE` option. I'm just waiting for the checks here to complete, and when everything works, I'll move the second commit to a different PR so that the first one can be part of the 1.11 release as you requested.

2022-03-21 18:04 UTC, digit-google commented
Done, the current PR only contains the fix to the output. The `--type` option was moved to my Github fork as https://github.com/digit-google/ninja/tree/inputs-type which I will rebase on top of upstream when this one is merged.
Let me know if this requires further changes. This now prints all inputs by default.

2022-03-22 10:37 UTC, jhasse approved these changes

2022-03-22 10:39 UTC, merged

2022-03-22 10:39 UTC, jhasse commented
Thanks!